# Generated by Django 3.1.1 on 2021-09-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0002_farm_name'),
        ('accounts', '0002_farmer_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Where the produce can be picked from.', max_length=30)),
                ('quantity', models.IntegerField(help_text='Kilograms of the harvest.')),
                ('sold', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.crop')),
                ('farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='MissionP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(auto_now_add=True)),
                ('complete', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('crop_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_crop', to='farm.crop')),
                ('farm_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_farm', to='farm.farm')),
                ('farm_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_farm', to='farm.farm')),
                ('farm_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_farm', to='farm.farm')),
                ('farm_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forth_farm', to='farm.farm')),
                ('farm_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_farm', to='farm.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='MissionA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(auto_now_add=True)),
                ('complete', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('animal_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_animal', to='farm.animal')),
                ('animal_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_animal', to='farm.animal')),
                ('animal_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_animal', to='farm.animal')),
                ('animal_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_animal', to='farm.animal')),
                ('animal_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_animal', to='farm.animal')),
                ('farm_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_farming', to='farm.farm')),
                ('farm_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_farming', to='farm.farm')),
                ('farm_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_farming', to='farm.farm')),
                ('farm_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_farming', to='farm.farm')),
                ('farm_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_farming', to='farm.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Animal_Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Where the produce can be picked from.', max_length=30)),
                ('quantity', models.IntegerField(help_text='Kilograms of the harvest.')),
                ('sold', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.crop')),
                ('farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmer')),
            ],
        ),
    ]
