# Generated by Django 3.1.1 on 2021-09-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_farm_name'),
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal_harvest',
            options={'verbose_name': 'Animal Harvest', 'verbose_name_plural': 'Animal Harvests'},
        ),
        migrations.AlterModelOptions(
            name='missiona',
            options={'verbose_name': 'Animal Kept', 'verbose_name_plural': 'Animals Kept'},
        ),
        migrations.AlterModelOptions(
            name='missionp',
            options={'verbose_name': 'Crop Planted', 'verbose_name_plural': 'Crops Planted'},
        ),
        migrations.AlterModelOptions(
            name='plant_harvest',
            options={'verbose_name': 'Plant Harvest', 'verbose_name_plural': 'Plant Harvests'},
        ),
        migrations.RenameField(
            model_name='missiona',
            old_name='animal_1',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='missiona',
            old_name='farm_1',
            new_name='farm',
        ),
        migrations.RenameField(
            model_name='missionp',
            old_name='farm_1',
            new_name='farm',
        ),
        migrations.RemoveField(
            model_name='missiona',
            name='animal_2',
        ),
        migrations.RemoveField(
            model_name='missiona',
            name='animal_3',
        ),
        migrations.RemoveField(
            model_name='missiona',
            name='animal_4',
        ),
        migrations.RemoveField(
            model_name='missiona',
            name='animal_5',
        ),
        migrations.RemoveField(
            model_name='missiona',
            name='farm_2',
        ),
        migrations.RemoveField(
            model_name='missiona',
            name='farm_3',
        ),
        migrations.RemoveField(
            model_name='missiona',
            name='farm_4',
        ),
        migrations.RemoveField(
            model_name='missiona',
            name='farm_5',
        ),
        migrations.RemoveField(
            model_name='missionp',
            name='crop_1',
        ),
        migrations.RemoveField(
            model_name='missionp',
            name='farm_2',
        ),
        migrations.RemoveField(
            model_name='missionp',
            name='farm_3',
        ),
        migrations.RemoveField(
            model_name='missionp',
            name='farm_4',
        ),
        migrations.RemoveField(
            model_name='missionp',
            name='farm_5',
        ),
        migrations.AddField(
            model_name='missionp',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_crop', to='farm.crop'),
        ),
    ]
