# Generated by Django 3.1.1 on 2021-09-15 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_auto_20210913_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_harvest',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farming.missiona'),
        ),
        migrations.AddField(
            model_name='plant_harvest',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farming.missionp'),
        ),
    ]
