# Generated by Django 3.1.1 on 2021-09-15 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0004_auto_20210915_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal_harvest',
            options={'ordering': ['-created'], 'verbose_name': 'Animal Harvest', 'verbose_name_plural': 'Animal Harvests'},
        ),
        migrations.AlterModelOptions(
            name='missiona',
            options={'ordering': ['-start_time'], 'verbose_name': 'Animal Kept', 'verbose_name_plural': 'Animals Kept'},
        ),
        migrations.AlterModelOptions(
            name='missionp',
            options={'ordering': ['-start_time'], 'verbose_name': 'Crop Planted', 'verbose_name_plural': 'Crops Planted'},
        ),
        migrations.AlterModelOptions(
            name='plant_harvest',
            options={'ordering': ['-created'], 'verbose_name': 'Plant Harvest', 'verbose_name_plural': 'Plant Harvests'},
        ),
        migrations.AddField(
            model_name='animal_harvest',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant_harvest',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
