# Generated by Django 3.1.1 on 2021-09-15 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210914_1031'),
        ('farming', '0005_auto_20210915_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_harvest',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_ward', to='accounts.ward'),
        ),
        migrations.AddField(
            model_name='missiona',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_ward', to='accounts.ward'),
        ),
        migrations.AddField(
            model_name='missionp',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_ward', to='accounts.ward'),
        ),
        migrations.AddField(
            model_name='plant_harvest',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='F_ward', to='accounts.ward'),
        ),
    ]
