# Generated by Django 3.1.1 on 2021-09-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_farmer_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(db_index=True, default='Kirinyaga', max_length=20),
        ),
    ]
