# Generated by Django 3.1.1 on 2021-09-09 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_farmer_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('animal_product', models.IntegerField(choices=[(0, 'Meat'), (1, 'Milk'), (2, 'Eggs')], help_text='The main product expected from the animal')),
                ('maturity_age', models.IntegerField(help_text='Months for animal to produce intended product')),
                ('animal_feed', models.IntegerField(choices=[(0, 'Plants'), (1, 'Feeds'), (2, 'Plants and Feeds')], help_text='The main food the animal feeds on')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('crop_type', models.IntegerField(choices=[(0, 'Food crop'), (1, 'Industrial crop')], default=0)),
                ('crop_product', models.IntegerField(choices=[(0, 'Cereal'), (1, 'Vegetative'), (2, 'Tuber')], default=0)),
                ('crop_growth', models.IntegerField(choices=[(0, 'Three months'), (1, 'Six months'), (2, 'Annual'), (3, 'Biannual'), (4, 'Perennial')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_size', models.IntegerField(help_text='Area of Farm in Metres 2')),
                ('water_availability', models.IntegerField(choices=[(0, 'All year'), (1, 'Seasonal'), (2, 'Hardly')], default=1)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.county')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmer')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ward')),
            ],
        ),
    ]
