# Generated by Django 3.1.1 on 2021-09-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='name',
            field=models.CharField(blank=True, help_text='A name to help you identify your farm', max_length=30, null=True),
        ),
    ]
